### ISSUE TITLE
"Executable `python` not found" when running this hook

### ISSUE THREAD

**Issue by PatrickSowinski** [radix-ai/auto-smart-commit#3]
Is this hook broken with the newest pre-commit?

I tried adding it to my project following the Readme, but I get the "Executable `python` not found" error. Should it point to python3 instead?
My other python pre-commit hooks are working fine (I'm using python3.10).
Maybe the language setting in `.pre-commit-hooks.yaml` in this repo should change from `script` to `python`?

======================

I tried adding this hook to my `pre-commit-config.yaml` like this:

```yaml
default_language_version:
  # default language version for each language used in the repository
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
        exclude: ".vscode|devcontainer.json"
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  [... more hooks ...]
  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit
```

And I ran `pre-commit install --hook-type prepare-commit-msg` as described in the Readme.
